name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY	}}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID	}}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME	}}
      ALGOLIA_SEARCH_ONLY_API_KEY: ${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY	}}
      GATSBY_DISQUS_NAME: ${{ secrets.GATSBY_DISQUS_NAME	}}
      GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID}}
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install && yarn lint
      - run: yarn run build
        env:
          CI: true
